# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/epg-grabber:${{ github.ref_name }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ env.IMAGE_TAG }} .
      
      - name: Push docker image
        run: docker push ${{ env.IMAGE_TAG }}
